# Generated by Django 4.2 on 2025-04-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='coices',
            field=models.CharField(choices=[('gendado', 'Agendado'), ('Realizado', 'Realizado'), ('Cancelado', 'Cancelado')], max_length=255),
        ),
    ]
