# Generated by Django 4.2 on 2025-04-08 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_alter_consulta_coices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='coices',
            new_name='status',
        ),
    ]
