# Generated by Django 4.2 on 2025-04-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_rename_coices_consulta_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
